first_project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from first_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('first_app/',include('first_app.urls')),
    path('users/',views.users,name='users'),
    path('signup/',views.new_users,name='new_users'),
]

first_project/first_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.DO_NOTHING,)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.DO_NOTHING,)
    date = models.DateTimeField()

    def __str__(self):
        return str(self.date)

class Users(models.Model):
    first_name = models.CharField(max_length=264,unique=False)
    last_name = models.CharField(max_length=264,unique=False)
    email = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

first_project/first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import Users

class NewUserFormName(forms.ModelForm):

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    verify_email = forms.CharField(label='Enter your email again:')

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("MAKE SURE EMAILS MATCH!")

    class Meta:
        model = Users
        fields = '__all__'

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic,AccessRecord,Webpage,Users
from . import forms
from first_app.forms import NewUserFormName

# Create your views here.

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {
        'text': 'hello world',
        'number':100,
        'access_records':webpages_list
    }
    return render(request,'first_app/index.html',context=date_dict)

def users(request):
    users_list = Users.objects.order_by('first_name')
    users_dict = {
        'user_records':users_list
    }
    return render(request,'first_app/users.html',context=users_dict)

def new_users(request):
    form = NewUserFormName()

    if request.method == 'POST':
        form = NewUserFormName(request.POST)

        if form.is_valid():
            form.save(commit=True)
            print("VALIDATION SUCCESS")
            print("FIRST NAME: " + form.cleaned_data['first_name'])
            print("LAST NAME: " + form.cleaned_data['last_name'])
            print("EMAIL: " + form.cleaned_data['email'])

            return index(request)
        else:
            print('ERROR FORM INVALID')

    return render(request,'first_app/sign_up_page.html',{'form':form})

def other(request):
    return render(request,'first_app/other.html')

def relative(request):
    return render(request,'first_app/relative_url_templates.html')

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'first_app:other' %}">Other</a></li>

        </ul>
      </div>

    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>


  </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}
  {% load static %}

    <h1>Hi Welcome to Django Level Two!</h1>
    <h2>Here are you're access records:</h2>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"99" }}</h1>

    <div class="djangotwo">
      {% if access_records %}
      <table>
        <thead>
          <th>Site Name</th>
          <th>Date Accessed</th>
        </thead>

        {% for acc in access_records %}
        <tr>
          <td>{{ acc.name }}</td>
          <td>{{ acc.date }}</td>
        </tr>

        {% endfor %}

      </table>

      {% else %}
      <p>NO ACCESS RECORDS FOUND!</p>
      {% endif %}

    </div>

    {% endblock %}

first_project/templates/first_app/original_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Test Page</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
  </head>
  <body>
    <h1>Hi this is a Picture of myself and my partner</h1>
    <img src="{% static "images/djangotest.jpg" %}" alt="Uh Oh, didn't show!">

  </body>
</html>

first_project/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance</h2>
    {% endblock %}

first_project/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES!</h1>
    <a href="{% url 'first_app:other' %}">THE OTHER PAGE</a><br>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a><br>
    <a href="{% url 'index' %}">LINK TO INDEX</a>

  </body>
</html>

first_project/templates/first_app/sign_up_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1>Fill out the form!</h1>
      <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Sign Up">
      </form>


    </div>

  </body>
</html>

first_project/templates/first_app/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Level Two</title>
  </head>
  <body>
    <h1>Here are your users:</h1>

    <div class="djangothree">
      {% if user_records %}

        {% for user in user_records %}
        <ol>
          <li>User Info</li>
            <ul>
              <li>First name: {{ user.first_name }}</li>
              <li>Last name: {{ user.last_name }}</li>
              <li>Email: {{ user.email }}</li>
            </ul>
        </ol>
        {% endfor %}

      {% else %}
      <p>NO USER RECORDS FOUND!</p>
      {% endif %}

    </div>

  </body>
</html>